### ISSUE TITLE
License detections explorer indicates 2 detections but displays just 1

### ISSUE THREAD

**Issue by johnmhoran** [aboutcode-org/scancode-workbench#562] opened 2023-04-21 21:47 UTC
Using SCWB 4.0.0rc2 on WSL2 Ubuntu-20.04 on Windows 10, the 2nd of 2 license detection entries on the left indicates detections in 2 files but only 1 is displayed.  A screenshot:

![image](https://user-images.githubusercontent.com/11096678/233738902-af07151b-f49c-4b41-a1e4-ca19ee17c962.png)

and what I think is the relevant excerpt from the JSON scan file:

```
  "license_detections": [
    {
      "identifier": "apache_2_0-8352cbe6-d199-3a43-cdc8-b14a837e2ce6",
      "license_expression": "apache-2.0",
      "detection_count": 1,
      "detection_log": []
    },
    {
      "identifier": "apache_2_0-c4e30bcd-ccfd-bbc3-d2f1-196ab911e47d",
      "license_expression": "apache-2.0",
      "detection_count": 2,
      "detection_log": []
    }
  ],
```

**Comment by AyanSinhaMahapatra** [comment] 2023-04-26 20:27
The issue is that this is a package license detection where we add this from the file license detection and so these have the same license detection identifier.

We should 

- show two entries in the `file_region` table, one for the `resource.license_detections` and another for `resource.package_data.license_detections`
- add another column (at first) in the `file_region` table called `from_package` and put :heavy_check_mark: or :x: accordingly for package/file detections


See the scancode result JSON attached (remove the .txt extension):
[kubernetes-model-common-5.12.2.jar-v32rc4results.json.txt](https://github.com/nexB/scancode-workbench/files/11336809/kubernetes-model-common-5.12.2.jar-v32rc4results.json.txt)

**Comment by OmkarPh** [comment] 2023-05-14 15:06
we can close this, as it's fixed & available in https://github.com/nexB/scancode-workbench/releases/tag/v4.0.0rc3

**Closed as completed** 2023-07-19 16:53 UTC
Labels: bug, ui, version4
