### ISSUE TITLE
Error while saving the SQLLite file into disk

### ISSUE THREAD

**Issue by RavindraAnnam** [aboutcode-org/scancode-workbench#414] opened 2019-12-11 06:03 UTC
Hi,
I am getting below error while saving the SQLLite file in to disk .I have given appropriate permissions still getting the error. Please help in this regard.

"You dont have permission to save in this location ".

But i have all permissions required .i tried to save in multiple locations still facing same issue .
I am attaching the error screenshot with this mail.

Regards,
Ravindra.
[SQL Lite Error.docx](https://github.com/nexB/scancode-workbench/files/3948684/SQL.Lite.Error.docx)

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-workbench are you running on?
* What version of scancode-toolkit was used to generate the scan file?

**Comment by steven-esser** [comment] 2019-12-11 18:44
@RavindraAnnam How did you extract the scancode-workbench release? There may be some permissions problems depending on the program you used or the way the archive was extracted. You could also try changing the permissions of the scancode-workbench folder; I am unfamiliar on how to do this in Windows, but I would think that there is a way to do this. 

Also, in the future, please upload either a `.png` or `.jpg` file for screenshots. `.docx` is a proprietary format and not suitable for images.

All in all, unless one of our windows users (@johnmhoran and/or @mjherzog) can reproduce this issue, this seems to a be a problem with your machine/permissions setup specifically and not with the scancode-workbench application.

**Comment by steven-esser** [comment] 2020-01-07 18:50
Closing this as @RavindraAnnam has not responded and this does not seem related to scancode-workbench in particular; it seems to be a permissions issue on @RavindraAnnam's side and cannot be reproduced.

**Closed as completed by steven-esser** 2020-01-07 18:50 UTC
